### ISSUE TITLE
The usage of taunts in DK/Pala Profile

### ISSUE THREAD

**Issue by GustafGSvensson** [darhanger/Ni-Profiles_Public#1]
Hi Darhanger, nice working profiles - Just have a question when it comes to paladin and DK tank regarding taunts - Paladin would be the aoe taunt + Hand of Recokning and DK would be using Dark Command.

Is it possible to remove the usage of taunt? Since the profiles are now encrypted I would like to either have a toggle for it or if you can share profiles without the taunt logic in it. Or if the taunt logic is already working as intended - I was tanking Emalon (VOA) and was tanking the ads and since you are tanking ads - you dont want to taunt the boss of the main tank - and vice versa. 

Is the taunts based on any logic expect tank having aggro? Maybe based on main tank/off tank options? - If not maybe better if you could share a profile that have taunts removed. 

Overall your profiles have good quality and working as intended!

**Comment by darhanger** [comment]
Make something with it in future update. Maybe make auto taunts working only in 5 man ppl. Idk now.

**Comment by GustafGSvensson** [comment]
Can you post/send me - profiles without the taunt logic for now? - Would most likely just be to remove the IDs and local queue right? - I love your work overall!

**Comment by darhanger** [comment]
im not home at now. And also im make lot of changes (Scott help). Im look to taunts.

**Comment by GustafGSvensson** [comment]
Thank you for your good work and help! - Looking forward to updates!

**Comment by darhanger** [comment]
What class u use in VoA? 
And which spell use ur tank for auto agro? U tanking mobs and ur tank auto agro Boss without targeting?
