### ISSUE TITLE
Getting DC Using AOE Toggle on DK Blood Profile

### ISSUE THREAD

**Issue by GustafGSvensson** [darhanger/Ni-Profiles_Public#2]
Hey, I am currently using your DK Tank Blood Profile and when I am using the AOE toggle - it performs the Death and Decay like normal but every few minutes I am getting a message saying "Next up in queue Death and Decay" and after a few seconds it disconnects me from server. I dont know the round about way to troubleshoot this myself,  but always happen with the AOE toggle and the ingame dialogue says "Next up is Death and Decay" - Not sure if it spamming the spell/query the server so much that it disconnects you?

**Comment by darhanger** [comment]
Copy this message to ni discord. Seems its problem not from my profile.
